### PR TITLE
Change: Text color inventory value

### PR DESCRIPTION
**Pull request by Varietyz**
Removed text color for inventory cost text from the config options, instead it displays the color based on the total value. 

Yellow for 1-99.999
White for 100.000 - 9.999.999
Green for 10.000.000 - 999.999.999
Blue for 1.000.000.000 +

image 
image 
image

And i dont have a billion to show that one.

But u get the idea, it accurately represents the value colors from in-game.
Adds to the immersion of the plugin imo :)

### CODE REVIEW

**Comment by Varietyz** [comment]
Also refined the Hub icon:
icon

**Comment by Varietyz** [comment]
Feel free to reach out to me via discord aswel.
Discord: JayBane

**Comment by hybridbrizz** [comment]
Let me take a look here. I think the plugin looks much better in your screenshot than it does by default. We would just need to work in a way to display profit / loss modes because that's a big part of the plugin.

**Comment by Varietyz** [comment]
> Let me take a look here. I think the plugin looks much better in your screenshot than it does by default. We would just need to work in a way to display profit / loss modes because that's a big part of the plugin.

Adding a + to profit or an underline would help in making it even more clear that its profit being displayed
or have it between caps 
total (profit) img

**Comment by Varietyz** [comment]
as to the current backgrounds and such, i did not change anything towards default.
i personally have set its config to display the border and background in a transparent way

**Comment by hybridbrizz** [comment]
+ / - before the amount is what I was thinking too. I'm going to make several changes that use the new text colors and change some of the config keys to establish new defaults for transparent backgrounds, borders, and right alignment. Also going to update the mouseover tooltip ledgers to use the new colors as well. Going to write all these changes in within a few days and get the update pushed up. This was a really good idea. Thank you for helping to make the plugin better and the new icons looks much better.

**Comment by Varietyz** [comment]
> Plus and minus before the amount is what I was thinking too. I'm going to make several changes that use the new text colors and change some of the config keys to establish new defaults for transparent backgrounds, borders, and right alignment. Also going to update the mouseover tooltip ledgers to use the new colors as well. Going to write all these changes in within a few days and get the update pushed up. This was a really good idea. Thank you for helping to make the plugin better and the new icons looks much better.

I was adding it to the tooltips and setting ur default configs to my current config setup :)

**Pull request merged**
